export const schedules = [
  {
    id: '1',
    name: 'Vitamin D3',
    form: 'Pill',
    amount: 1,
    frequency: 'Daily',
    time: '08:00 AM',
    medicineTime: 'After food',
    action: 'Take',
    startDate: '2025-07-01',
    endDate: '2025-08-01',
    upcoming: true,
    isTaken: false,
    notes: 'Take with a full glass of water.',
    medicineType: 'Supplement',
    repeat: 'Daily',
  },
  {
    id: '2',
    name: 'Omega-3 Fish Oil',
    form: 'Drop',
    amount: 2,
    frequency: 'Daily',
    time: '12:00 PM',
    medicineTime: 'With food',
    action: 'Take',
    startDate: '2025-07-05',
    endDate: '2025-08-05',
    upcoming: true,
    isTaken: true,
    notes: 'Avoid taking on an empty stomach.',
    medicineType: 'Supplement',
    repeat: 'Daily',
  },
  {
    id: '3',
    name: 'Calcium Citrate',
    form: 'Tablet',
    amount: 1,
    frequency: 'Daily',
    time: '09:00 AM',
    medicineTime: 'Before food',
    action: 'Take',
    startDate: '2025-06-25',
    endDate: '2025-07-25',
    upcoming: false,
    isTaken: true,
    notes: 'Take separately from iron supplements.',
    medicineType: 'Prescription',
    repeat: 'Daily',
  },
  {
    id: '4',
    name: 'Probiotic Complex',
    form: 'Capsule',
    amount: 1,
    frequency: 'Every 2 Days',
    time: '10:30 AM',
    medicineTime: 'Empty stomach',
    action: 'Take',
    startDate: '2025-07-10',
    endDate: '2025-08-10',
    upcoming: true,
    isTaken: false,
    notes: 'Do not take with hot drinks.',
    medicineType: 'Supplement',
    repeat: 'Every 2 Days',
  },
  {
    id: '5',
    name: 'Multivitamin',
    form: 'Syrup',
    amount: 1,
    frequency: 'Daily',
    time: '07:00 AM',
    medicineTime: 'After food',
    action: 'Skip',
    startDate: '2025-06-20',
    endDate: '2025-07-20',
    upcoming: false,
    isTaken: false,
    notes: 'Contains iron. May cause constipation.',
    medicineType: 'Supplement',
    repeat: 'Daily',
  },
  {
    id: '6',
    name: 'Zinc Gluconate',
    form: 'Tablet',
    amount: 1,
    frequency: 'Every other day',
    time: '06:00 PM',
    medicineTime: 'With food',
    action: 'Take',
    startDate: '2025-07-12',
    endDate: '2025-08-12',
    upcoming: true,
    isTaken: false,
    notes: 'Helps immune system.',
    medicineType: 'Supplement',
    repeat: 'Every other day',
  },
  {
    id: '7',
    name: 'Magnesium Glycinate',
    form: 'Tablet',
    amount: 2,
    frequency: 'Twice Daily',
    time: '08:00 AM',
    medicineTime: 'After food',
    action: 'Take',
    startDate: '2025-07-01',
    endDate: '2025-07-30',
    upcoming: true,
    isTaken: false,
    notes: 'Helps with sleep and cramps.',
    medicineType: 'Supplement',
    repeat: 'Twice Daily',
  },
  {
    id: '8',
    name: 'Iron Ferrous Sulfate',
    form: 'Tablet',
    amount: 1,
    frequency: 'Daily',
    time: '11:00 AM',
    medicineTime: 'Before food',
    action: 'Take',
    startDate: '2025-06-28',
    endDate: '2025-08-28',
    upcoming: true,
    isTaken: true,
    notes: 'Take with vitamin C to enhance absorption.',
    medicineType: 'Prescription',
    repeat: 'Daily',
  },
  {
    id: '9',
    name: 'Vitamin C',
    form: 'Tablet',
    amount: 1,
    frequency: 'Daily',
    time: '03:00 PM',
    medicineTime: 'With food',
    action: 'Take',
    startDate: '2025-07-01',
    endDate: '2025-08-01',
    upcoming: true,
    isTaken: false,
    notes: 'Boosts immunity.',
    medicineType: 'Supplement',
    repeat: 'Daily',
  },
  {
    id: '10',
    name: 'Ashwagandha',
    form: 'Capsule',
    amount: 1,
    frequency: 'Daily',
    time: '09:30 PM',
    medicineTime: 'After food',
    action: 'Take',
    startDate: '2025-07-01',
    endDate: '2025-08-01',
    upcoming: true,
    isTaken: false,
    notes: 'Adaptogen - helps with stress.',
    medicineType: 'Herbal',
    repeat: 'Daily',
  },
];
